-- Optional employee details for profile creation, viewing, and updating.
alter table profiles
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists display_name text,
  add column if not exists company text,
  add column if not exists employee_group text,
  add column if not exists employment_type text,
  add column if not exists employee_sub_type text,
  add column if not exists date_of_joining date,
  add column if not exists probation_start_date date,
  add column if not exists notice_days integer check (notice_days >= 0),
  add column if not exists date_of_retirement date,
  add column if not exists epf_contract_no text,
  add column if not exists mobile text,
  add column if not exists personal_email text,
  add column if not exists company_email text,
  add column if not exists preferred_contact_email text,
  add column if not exists preferred_email text,
  add column if not exists emergency_contact_name text,
  add column if not exists emergency_phone text,
  add column if not exists relation text,
  add column if not exists secondary_emergency_contact text,
  add column if not exists secondary_emergency_phone text,
  add column if not exists secondary_relation text,
  add column if not exists gender text,
  add column if not exists date_of_birth date,
  add column if not exists nic text;
